apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource
  chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  release: "{{ .Release.Name }}"
  heritage: "{{ .Release.Service }}"
data:
{{- if eq .Values.images.classifier "wildfly12" }}
  JDBCURL: {{ .Values.jdbcUrl }}
  USER: {{ .Values.userDataBase}}
  PASSWORD: {{ .Values.passwordDataBase}}
  security-ear-ds.xml: |- 
    <datasources>
      <datasource jta="true" jndi-name="jdbc/security-earDS" pool-name="SecurityWeb" use-ccm="false" enabled="true">
        <connection-url>{{ .Values.jdbcUrl }}</connection-url>
        <driver>sqlserver</driver>
        <new-connection-sql>select getDate()</new-connection-sql>
        <transaction-isolation>TRANSACTION_READ_UNCOMMITTED</transaction-isolation>
        <pool>
          <min-pool-size>1</min-pool-size>
          <max-pool-size>100</max-pool-size>
        </pool>
        <security>
          <user-name>{{ .Values.userDataBase}}</user-name>
          <password>{{ .Values.passwordDataBase}}</password>
        </security>
        <validation>
          <check-valid-connection-sql>select getDate()</check-valid-connection-sql>
          <validate-on-match>false</validate-on-match>
          <background-validation>false</background-validation>
        </validation>
        <statement>
          <share-prepared-statements>false</share-prepared-statements>
        </statement>
      </datasource>
    </datasources>
  myinvest-ear-ds.xml: |- 
    <datasources>
      <datasource jta="true" jndi-name="jdbc/myinvest-earDS" pool-name="myinvestWeb" use-ccm="false" enabled="true">
        <connection-url>{{ .Values.jdbcUrl }}</connection-url>
        <driver>sqlserver</driver>
        <new-connection-sql>select getDate()</new-connection-sql>
        <transaction-isolation>TRANSACTION_READ_UNCOMMITTED</transaction-isolation>
        <pool>
          <min-pool-size>1</min-pool-size>
          <max-pool-size>100</max-pool-size>
        </pool>
        <security>
          <user-name>{{ .Values.userDataBase}}</user-name>
          <password>{{ .Values.passwordDataBase}}</password>
        </security>
        <validation>
          <check-valid-connection-sql>select getDate()</check-valid-connection-sql>
          <validate-on-match>false</validate-on-match>
          <background-validation>false</background-validation>
        </validation>
        <statement>
          <share-prepared-statements>false</share-prepared-statements>
        </statement>
      </datasource>
    </datasources>
{{- end }}
{{- if eq .Values.images.classifier "liberty" }}
  myinvest-server.xml: |-{{ .Values.myinvestserverxml | nindent 4 }}
  security-server.xml: |-{{ .Values.securityserverxml | nindent 4 }}
{{- end }}
{{- if .Values.jvmoptions.custom }}
  jvm.options: |-{{ .Values.jvmoptions.value | nindent 4 }}
{{- end }}