apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myinvestsite-deployment
  chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  release: "{{ .Release.Name }}"
  heritage: "{{ .Release.Service }}"
  labels:
    app: myinvestsite
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myinvestsite
  template:
    metadata:
      annotations:
          checksum/config: {{ include (print $.Template.BasePath "/myinvestsite-configmaps.yaml") . | sha256sum }}
      labels:
        app: myinvestsite
    spec:
      imagePullSecrets:
      - name: "acr-credentials"
      containers:
      - name: myinvestsite
        image: temasistemas.azurecr.io/nginx-base:latest
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: myinvest-nginx
          mountPath: /etc/nginx/conf.d/myinvest-nginx.conf
          subPath: myinvest-nginx.conf
        - name: myinvest-crt
          mountPath: /etc/nginx/myinvest.crt
          subPath: myinvest.crt
        - name: myinvest-key
          mountPath: /etc/nginx/myinvest.key
          subPath: myinvest.key          
      volumes:
      - name: myinvest-crt
        configMap:
          name: myinvest-nginx
          items:
          - key: myinvest.crt
            path: myinvest.crt
      - name: myinvest-key
        configMap:
          name: myinvest-nginx
          items:
          - key: myinvest.key
            path: myinvest.key
      - name: myinvest-nginx
        configMap:
          name: myinvest-nginx
          items:
          - key: myinvest-nginx.conf
            path: myinvest-nginx.conf