apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-ear-deployment
  labels:
    app: myapp-ear
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      version : latest
      app: myapp-ear
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/datasource-configmaps.yaml") . | sha256sum }}
      labels:
        version: latest
        app: myapp-ear
    spec:
      imagePullSecrets:
      - name: "acr-credentials"
      containers:
      - name: myapp-ear
{{- if eq .Values.images.classifier "liberty" }}
        image: laersondev.azurecr.io/myapp-liberty:{{ .Values.images.myapp }}
{{- else -}}
        image: laersondev.azurecr.io/myapp:{{ .Values.images.myapp }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /myapp
            port: {{ .Values.myapp.port }}
          initialDelaySeconds: 120
          periodSeconds: 120
          timeoutSeconds: 20
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - containerPort: {{ .Values.myapp.port }}
        volumeMounts:
        - name: deployments-ds-volume
{{- if eq .Values.images.classifier "liberty" }}
          mountPath: /opt/liberty17/usr/servers/defaultServer/server.xml
          subPath: server.xml
{{- else -}}
          mountPath: /opt/wildfly12/standalone/deployments/myapp-ear-ds.xml
          subPath: myapp-ear-ds.xml
{{- end }}
{{- if  .Values.jvmoptions.custom }}
        - name: jvmoptions-volume
          mountPath: /opt/liberty17/usr/servers/defaultServer/jvm.options
          subPath: jvm.options
{{- end }}
        -name: myapp-arquivos-volume
          mountPath: /myappdata
      volumes:
      - name: deployments-ds-volume
        configMap:
          name: datasource
          items:
{{- if eq .Values.images.classifier "liberty" }}
          - key: myapp-server.xml
            path: server.xml
{{- else -}}
          - key: myapp-ear-ds.xml
            path: myapp-ear-ds.xml
{{- end}}
{{- if .Values.jvmoptions.custom }}
      - name: jvmoptions-volume
        configMap:
          name: datasource
          items:
          - key: jvm.options
            path: jvm.options
{{- end }}
      - name: myapp-arquivos-volume
        hostPath: 
          path: /myappdata
        persistentVolumeClaim:
          claimName: myapp-ear-pvc